services:
  - type: web
    name: connectsphere-backend
    env: node
    plan: free
    region: oregon
    repo: https://github.com/Dileepreddy974/connectSphere
    branch: main
    root: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
    secrets:
      - key: MONGODB_URI
      - key: JWT_SECRET
      - key: CLIENT_URL